# Generated by Django 4.1 on 2023-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videojuego", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidas",
            name="puntaje",
            field=models.IntegerField(),
        ),
    ]
