# Generated by Django 4.1 on 2023-03-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videojuego", "0002_alter_partidas_puntaje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidas",
            name="id_usuarios",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videojuego.usuarios"
            ),
        ),
    ]
