# Generated by Django 4.2 on 2023-04-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0003_alter_partidas_id_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lista', models.IntegerField()),
                ('grupo', models.CharField(max_length=60)),
                ('progreso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.CharField(max_length=60)),
                ('completado', models.BooleanField()),
                ('estudianteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_id', to='videojuego.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mundo', models.IntegerField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Partidas',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
